spring:
  application:
    name: audio-service

server:
  port: 7501

eureka:
  client:
    service-url:
      defaultZone: http://49.127.70.209:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:logback.xml